# Base image
FROM ubuntu:16.04

# Set working directory
WORKDIR /backend

# Copy project file to working directory
COPY ./backend-example-docker-master /backend

# Do update, install curl, node and dependencies
# Do purge
RUN apt-get update && apt-get install curl -y \
&& curl -sL https://deb.nodesource.com/setup_10.x | bash && apt-get update \
&& apt-get install -y nodejs \ 
&& npm install \
&& apt-get purge -y --auto-remove curl \
&& rm -rf /var/lib/apt/lists/*

# Expose port 5000
EXPOSE 8000

# Set FRONT_URL variable
ENV FRONT_URL=http://localhost:5000

# Build and server in production mode in folder /dist
ENTRYPOINT npm start
