# Set Base image for startup build-stage
FROM node:alpine as build-stage

# Set working directory for startup build-stage
WORKDIR /frontend

# Copy project file to working directory startup build-stage
COPY ./frontend-example-docker-master /frontend

# Do update, install node and dependencies
# RUN apk update & npm install
RUN apk update && npm install

# Start new multi-stage build 
FROM node:alpine

# Set working directory for the new build stage
WORKDIR /frontend

# Copy /frontend directory of startup build to new build stage
COPY --from=build-stage /frontend /frontend

# Add user account named app and change ownership of /frontend folder
RUN adduser -S app && \
chown -R app /frontend

# Switch using app (non-root) account
USER app

# Expose port 5000
EXPOSE 5000

# Set API_URL enviroment variable
ENV API_URL=http://localhost:8000

# Build and server in production mode in folder /dist
CMD npm start
