# Set Base image for startup build-stage 
FROM node:alpine as build-stage

# Set working directory for startup build-stage
WORKDIR /usr/app

# Do update, install node and dependencies
COPY ./simpleweb/package.json .
RUN npm install

# copy rest of the files to working directory
COPY ./simpleweb .

# Start new multi-stage build 
FROM node:alpine

# Set working directory for the new build stage
WORKDIR /usr/app

# Copy /frontend directory of startup build to new build stage
COPY --from=build-stage /usr/app /usr/app

# Add user account named app and change ownership of /frontend folder
RUN adduser -S app && \
chown -R app /usr/app

# Switch using app (non-root) account
USER app

# Default command
CMD ["npm", "start"]
