# Base image
FROM node:13

# Set working directory
WORKDIR /frontend

# Do update and install curl
RUN apt update && apt install -y curl

# Copy project file to working directory
COPY ./frontend-example-docker-master /frontend

# Install packages and depencies
RUN npm install

# Expose port 5000
EXPOSE 5000

# Build and server in production mode in folder /dist
ENTRYPOINT npm start
